### ISSUE TITLE
about no c2f metric

### ISSUE THREAD

**Issue by llianxu** [IntelLabs/baa-ngp#2]
Hi！thanks for your impressive work！I have a question about no c2f metric. When I try this command without --c2f as below.  THE metric is better than paper said in lego scene. I want to know if you have any thoughts on this situation？
`python baangp/train_baangp.py --scene [lego] --data-root [your_data_root] --save-dir [your_save_dir] `

**Comment by sainanl** [comment]
Thank you for your interest. What we have observed is that using c2f yields overall better results than without it. One run with the lego data may yield comparable or better results. Our reported numbers are overall a bit more conservative and are based on multiple run repeats. Hope this helps.
