### ISSUE TITLE
Error reported about CUDA

### ISSUE THREAD

**Issue by Allen070206** [IntelLabs/baa-ngp#3]
When I finished my training, CUDA error occurred in the stage of generating training indicators:
RuntimeError: CUDA error: invalid configuration argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

![image](https://github.com/IntelLabs/baa-ngp/assets/31239123/32fb6b8a-efad-4c2f-8896-f1369750afe2)
What is the reason？please!

**Comment by sainanl** [comment]
Hi, sorry for the late reply. I just found some time to verify the runs and update the repo. This should not be an issue anymore.
