### ISSUE TITLE
Regarding the handling and training of the Local Light Field Fusion (LLFF) dataset

### ISSUE THREAD

**Issue by Allen070206** [IntelLabs/baa-ngp#4]
Hello sainanl, thank you for your excellent work. I am particularly interested in the part of the code pertaining to the processing and training of the LLFF dataset. May I ask if this section has already been debugged? I would very much appreciate the opportunity to learn about the specific implementation process. Many thanks!

**Comment by sainanl** [comment]
Thanks for your interest! I may have some time to get back to the code release for LLFF later this year.

**Comment by Allen070206** [comment]
ok，thank your reply
